version: "3.1"
services:
    apache:
        image: httpd:2.4-alpine
        restart: always
        container_name: xiavic-apache
        ports:
            - "${XIAVIC_APACHE_PORT}:80"
        volumes:
            - ./application/:/usr/local/apache2/htdocs/:delegated
            - ./docker/apache/logs:/var/log/apache2:delegated
